site_name: School Of SRE
docs_dir: courses
theme:
  name: material
  logo: img/sos.png
  favicon: img/favicon.ico
  custom_dir: overrides
extra_css:
    - stylesheets/custom.css
nav:
- Home: index.md
- Fundamentals Series:
    - Linux Basics:
        - Introduction: linux_basics/intro.md
        - Command Line Basics: linux_basics/command_line_basics.md
        - Server Administration: linux_basics/linux_server_administration.md
        - Conclusion: linux_basics/conclusion.md
    - Git:
        - Git Basics: git/git-basics.md
        - Working With Branches: git/branches.md
        - Github and Hooks: git/github-hooks.md
        - Conclusion: git/conclusion.md
    - Linux Networking:
        - Introduction: linux_networking/intro.md
        - DNS: linux_networking/dns.md
        - UDP: linux_networking/udp.md
        - HTTP: linux_networking/http.md
        - TCP: linux_networking/tcp.md
        - Routing: linux_networking/ipr.md
        - Conclusion: linux_networking/conclusion.md
- Python and Web:
    - Introduction: python_web/intro.md
    - Some Python Concepts: python_web/python-concepts.md
    - Python, Web and Flask: python_web/python-web-flask.md
    - The URL Shortening App: python_web/url-shorten-app.md
    - Conclusion: python_web/sre-conclusion.md
- Data:
    - Relational Databases:
        - Introduction: databases_sql/intro.md
        - Key Concepts: databases_sql/concepts.md
        - MySQL: databases_sql/mysql.md
        - InnoDB: databases_sql/innodb.md
        - Operational Concepts: databases_sql/operations.md
        - Lab: databases_sql/lab.md
        - Conclusion: databases_sql/conclusion.md
    - NoSQL:
        - Introduction: databases_nosql/intro.md
        - Key Concepts: databases_nosql/key_concepts.md
        - Conclusion:  databases_nosql/further_reading.md
    - Big Data:
        - Introduction: big_data/intro.md
        - Evolution and Architecture of Hadoop: big_data/evolution.md
        - Conclusion: big_data/tasks.md
- Systems Design:
    - Introduction: systems_design/intro.md
    - Scalability: systems_design/scalability.md
    - Availability: systems_design/availability.md
    - Fault Tolerance: systems_design/fault-tolerance.md
    - Conclusion: systems_design/conclusion.md
- Metrics and Monitoring:
    - Introduction: metrics_and_monitoring/introduction.md
    - Command-line Tools: metrics_and_monitoring/command-line_tools.md
    - Third-party Monitoring: metrics_and_monitoring/third-party_monitoring.md
    - Proactive Monitoring with Alerts: metrics_and_monitoring/alerts.md
    - Best Practices for Monitoring: metrics_and_monitoring/best_practices.md
    - Observability: metrics_and_monitoring/observability.md
    - Conclusion: metrics_and_monitoring/conclusion.md
- Security:
    - Introduction: security/intro.md
    - Fundamentals of Security: security/fundamentals.md
    - Network Security: security/network_security.md
    - Threat, Attacks & Defences: security/threats_attacks_defences.md
    - Writing Secure code: security/writing_secure_code.md
    - Conclusion: security/conclusion.md
- Contribute: CONTRIBUTING.md
- Code of Conduct: CODE_OF_CONDUCT.md
- SRE Community: sre_community.md
copyright: "Copyright 2020 LinkedIn Corporation. All Rights Reserved. Licensed under the Creative Commons Attribution 4.0 International Public License"
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/linkedin/school-of-sre
