site_name: SchoolOfSRE
docs_dir: courses
theme:
  name: material
  logo: img/sos.png
  favicon: img/favicon.ico
plugins: []
nav:
- Home: index.md
- Fundamentals Series:
    - Git:
        - Git Basics: git/git-basics.md
        - Working With Branches: git/branches.md
        - Github and Hooks: git/github-hooks.md
    - Linux Networking:
        - Introduction: linux_networking/intro.md
        - DNS: linux_networking/dns.md
        - UDP: linux_networking/udp.md
        - HTTP: linux_networking/http.md
        - TCP: linux_networking/tcp.md
        - Routing and Conclusion: linux_networking/ipr.md
- Python and Web:
    - Introduction: python_web/intro.md
    - Some Python Concepts: python_web/python-concepts.md
    - Python, Web and Flask: python_web/python-web-flask.md
    - The URL Shortening App: python_web/url-shorten-app.md
    - SRE Aspects of The App and Conclusion: python_web/sre-conclusion.md
- Systems Design:
    - Introduction: systems_design/intro.md
    - Scalability: systems_design/scalability.md
    - Availability: systems_design/availability.md
    - Fault Tolerance: systems_design/fault-tolerance.md
    - Conclusion: systems_design/conclusion.md
- Data:
    - Big Data:
        - Introduction: big_data/intro.md
        - Overview of Big Data: big_data/overview.md
        - Usage of Big Data techniques: big_data/usage.md
        - Evolution of Hadoop: big_data/evolution.md
        - Architecture of Hadoop: big_data/architecture.md
        - Tasks and conclusion: big_data/tasks.md
- Security:
    - Introduction: security/intro.md
    - Fundamentals of Security: security/fundamentals.md
    - Network Security: security/network_security.md
    - Threat, Attacks & Defences: security/threats_attacks_defences.md
    - Writing Secure code: security/writing_secure_code.md  
